NAME: 'stmap'

MODEL:
    input_nc: 3
    output_nc: 2
    if_sigmoid: False
    emd: 16
    filters: 
        - 16
        - 32
        - 64
        - 128
        - 256
    finetuning: False
    show_feature : True

TRAIN:
    resume: False
    if_valid: True
    if_seg: True
    model_name: "AttentionUnet"
    cache_path: '../caches/'
    save_path: '../models/'
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    affs0_weight: 1
    mask_weight: 0.5
    dis_mode: 'ours'
    ema: False
    ema_decay: 0.99
    sharing_weights: True
    self_emb: 1.0
    dis_emb: 1.0
    ct_weight: 0.0
    deep_weight: 1

    opt_type: 'adam'  # sgd
    lr_mode: 'fixed'
    total_iters: 1000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 50
    show_freq: 50
    valid_freq: 50
    save_freq: 100
    decay_iters: 100000
    weight_decay: ~
    power: 1.5

    batch_size: 4
    num_workers: 1
    if_cuda: True

    random_seed: 555  # -1 is none

DATA:
    remove_training_set: ~
    size: 512
    num_train: 108
    data_folder: '../StmapData/'
    padding: True
    separate_weight: True
    background: False
    shifts:
        - 1
        - 3
        - 5
        - 9
        - 27
    neighbor: 8
    obj_neighbor_max: 100 # maximum possinle adjacent trajectories
    strides: 
        - 5
        - 5
    if_dilate: True
    widen_way: True
    if_scale_aug: True
    if_filp_aug: False
    if_rotation_aug: False
    if_intensity_aug: False
    if_elastic_aug: False

TEST:
    pad: 0
    model_name: ''